#!/bin/bash
#SBATCH --job-name=CIS_SEIR
#SBATCH --output=slurm/out_%a.txt
#SBATCH --error=slurm/err_%a.txt
#SBATCH --time=00:30:00
#SBATCH --cpus-per-task=1
#SBATCH --mem=50GB
#SBATCH -A mrc-bsu-sl2-cpu
#SBATCH --partition=icelake-himem
#SBATCH --array=1-800

## Initialize work environment like
. /etc/profile.d/modules.sh                # Leave this line (enables the module command)
module purge                               # Removes all modules still loaded
module load rhel7/default-ccl              # REQUIRED - loads the basic environment
module load gcc/11
module load R/4.2.0-icelake

echo "hi"
cd ..
Rscript 10_sims/run.R $SLURM_ARRAY_TASK_ID