#!/bin/bash
#SBATCH --job-name=sim_output
#SBATCH --output=slurm/output_out.txt
#SBATCH --error=slurm/output_err.txt
#SBATCH --time=05:00:00
#SBATCH --cpus-per-task=4
#SBATCH --mem=20GB
#SBATCH -A mrc-bsu-sl2-cpu
#SBATCH --partition=cclake

## Initialize work environment like
. /etc/profile.d/modules.sh                # Leave this line (enables the module command)
module purge                               # Removes all modules still loaded
module load rhel7/default-ccl              # REQUIRED - loads the basic environment
module load gcc/11
module load R/4.2.0

cd ..
Rscript 10_sims/output.R