#!/bin/bash
#SBATCH --job-name=SIM_infer
#SBATCH --output=slurm/out_%a.txt
#SBATCH --error=slurm/err_%a.txt
#SBATCH --time=25:00:00
#SBATCH --cpus-per-task=4
#SBATCH --mem=8GB
#SBATCH -A mrc-bsu-sl2-cpu
#SBATCH --partition=cclake
#SBATCH --array=1-13

## Initialize work environment like
. /etc/profile.d/modules.sh                # Leave this line (enables the module command)
module purge                               # Removes all modules still loaded
module load rhel7/default-ccl              # REQUIRED - loads the basic environment
module load gcc/11
module load R/4.2.0

cd ..
Rscript 20_sims/run.R $SLURM_ARRAY_TASK_ID